services:
  postgres-auth:
    image: postgres:16.14-alpine
    container_name: postgres_auth_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=auth-service
    ports:
      - "5433:5432"
    volumes:
      - pgdata_auth:/var/lib/postgresql/data

  auth-service: 
    build: ./auth-service
    container_name: auth_service
    ports:
      - "8080:8080"
    depends_on:
      - postgres-auth

  postgres-order:
    image: postgres:16.14-alpine
    container_name: postgres_order_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=order-service
    ports:
      - "5434:5432"
    volumes:
      - pgdata_order:/var/lib/postgresql/data

  order-service:
    build: ./order-producer-service
    container_name: order_service
    ports:
      - "8081:8081"
    depends_on:
      - postgres-order
      - rabbitmq

  postgres-batch:
    image: postgres:16.14-alpine
    container_name: postgres_batch_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=batch-service
    ports:
      - "5435:5432"
    volumes:
      - pgdata_batch:/var/lib/postgresql/data

  mongo-batch:
    image: mongo:7.0
    container_name: mongo_batch_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata_batch:/data/db

  batch-service:
    build: ./batch-service
    container_name: batch_service
    ports:
      - "8082:8082"
    depends_on:
      - postgres-batch
      - mongo-batch
      - rabbitmq

  postgres-stock:
    image: postgres:16.14-alpine
    container_name: postgres_stock_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=stock-service
    ports:
      - "5436:5432"
    volumes:
      - pgdata_stock:/var/lib/postgresql/data

  stock-service:
    build: ./stock-service
    container_name: stock-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres-stock
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  pgdata_auth:
  pgdata_order:
  pgdata_batch:
  mongodata_batch:
  pgdata_stock:
  rabbitmq_data: